ignore:
  - 'lib/ryo/object_mixin.rb':
    - Layout/IndentationWidth
    - Layout/ElseAlignment
    - Layout/EndAlignment
  - 'readme_examples/rb/*.rb':
    - Style/LambdaCall 
    - Style/TrailingCommaInHashLiteral
    - Layout/ExtraSpacing
  - '**/*.rb':
    - Layout/ParameterAlignment
    - Layout/ArgumentAlignment
    - Lint/AssignmentInCondition
    - Lint/ConstantDefinitionInBlock
    - Layout/MultilineOperationIndentation
    - Layout/MultilineMethodCallIndentation
    - Style/NilComparison
    - Style/LambdaCall
