ignore:
  - 'readme_examples/rb/*.rb':
    - Style/LambdaCall 
    - Style/TrailingCommaInHashLiteral
  - '**/*.rb':
    - Layout/ParameterAlignment
    - Layout/ArgumentAlignment
    - Lint/AssignmentInCondition
    - Lint/ConstantDefinitionInBlock
    - Layout/MultilineOperationIndentation
